/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        StandardCalculator calc = new StandardCalculator();
        calc.add(8,3);
        System.out.println(calc.getResult());
        calc.subtract(12,2);
        System.out.println(calc.getResult());
        calc.multiply(5,3);
        System.out.println(calc.getResult());
        calc.divide(16,2);
        System.out.println(calc.getResult());
                System.out.println(new App().getGreeting());
    }
}
